name: Deploy MongoDB to OpenShift

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in OpenShift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: https://api.rm1.0a51.p1.openshiftapps.com:6443
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}

      - name: Set OpenShift project
        run: oc project my-project-name

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Deploy MongoDB with Helm
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm upgrade --install mongodb bitnami/mongodb \
            -f values.yaml
