name: Deploy MongoDB to OpenShift

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Instalar OpenShift CLI
      - name: Install OpenShift CLI
        run: |
          curl -L https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz | tar xz
          sudo mv oc /usr/local/bin/
          oc version

      # 3️⃣ Loguearse en OpenShift usando token
      - name: Log in OpenShift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: https://api.rm1.0a51.p1.openshiftapps.com:6443
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}

      # 4️⃣ Seleccionar el proyecto/OpenShift namespace
      - name: Set OpenShift project
        run: oc project lpintofsgrp-dev

      # 5️⃣ Instalar Helm
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      # 6️⃣ Agregar repositorio de Bitnami
      - name: Add Bitnami Helm repo
        run: helm repo add bitnami https://charts.bitnami.com/bitnami

      # 7️⃣ Desplegar MongoDB usando values.yaml
      - name: Deploy MongoDB with Helm
        run: |
          helm upgrade --install mongodb bitnami/mongodb \
            -f values.yaml
          
      # 8️⃣ (Opcional) Mostrar secret generado por MongoDB
      - name: Show generated MongoDB root password
        run: |
          echo "MongoDB root password:"
          oc get secret mongodb -o jsonpath="{.data.mongodb-root-password}" | base64 --decode
